FROM node:10-alpine

RUN apk --no-cache --virtual add \
    python \
    python3 \
    make \
    g++

RUN python --version

# Create app directory and set as working directory
RUN mkdir -p /opt/frontend
WORKDIR /opt/frontend
  
EXPOSE 3000
