version: '3'

services:
  nginx:
    restart: "no"
  # certbot:
  #   restart: "no"
  postgres:
    restart: "no"
  redis:
    restart: "no"
  frontend:
    ports:
      - 3000:3000
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
    restart: "no"
    command: sh -c 'yarn && yarn start'
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - WAIT_HOSTS=postgres:5432,db_cache:6379
    restart: "no"
    command: sh -c 'yarn && /wait && yarn start:dev'

  postgres:
    ports:
      - 5432:5432
