FROM node:10-alpine

RUN apk --no-cache --virtual add \
    python \
    python3 \
    make \
    g++
  
# wait for other services
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.5.1/wait /wait
RUN chmod +x /wait

RUN python --version
  
# RUN npm install -g yarn

# Create app directory and set as working directory
RUN mkdir -p /opt/backend
WORKDIR /opt/backend

EXPOSE 3000
