version: '3'

services:
  nginx-admin:
    restart: "no"
  certbot:
    restart: "no"
  postgres:
    restart: "no"
  redis:
    restart: "no"
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - WAIT_HOSTS=postgres:5432,db_cache:6379
    restart: "no"
    command: sh -c 'yarn && /wait && yarn start:dev'

  postgres:
    ports:
      - 5432:5432
