// 1. create user with login
export const CREATE_WITH_LOGIN_REQUEST = '@@/USER/CREATE_WITH_LOGIN_REQUEST';
export const CREATE_WITH_LOGIN_SUCCESS = '@@/USER/CREATE_WITH_LOGIN_SUCCESS';
export const CREATE_WITH_LOGIN_FAILURE = '@@/USER/CREATE_WITH_LOGIN_FAILURE';

// 2. create user
export const CREATE_REQUEST = '@@/USER/CREATE_REQUEST';
export const CREATE_SUCCESS = '@@/USER/CREATE_SUCCESS';
export const CREATE_FAILURE = '@@/USER/CREATE_FAILURE';
