// 1. get journals
export const GET_JOURNALS_REQUEST =
  '@@/ACCOUNTING/JOURNAL/GET_JOURNALS_REQUEST';
export const GET_JOURNALS_SUCCESS =
  '@@/ACCOUNTING/JOURNAL/GET_JOURNALS_SUCCESS';
export const GET_JOURNALS_FAILURE =
  '@@/ACCOUNTING/JOURNAL/GET_JOURNALS_FAILURE';

// 2. create journal entries
export const CREATE_JOURNAL_REQUEST =
  '@@/ACCOUNTING/JOURNAL/CREATE_JOURNAL_REQUEST';
export const CREATE_JOURNAL_SUCCESS =
  '@@/ACCOUNTING/JOURNAL/CREATE_JOURNAL_ENTRIES_SUCCESS';
export const CREATE_JOURNAL_FAILURE =
  '@@/ACCOUNTING/JOURNAL/CREATE_JOURNAL_ENTRIES_FAILURE';

// 3. update journal entries
export const UPDATE_JOURNAL_REQUEST =
  '@@/ACCOUNTING/JOURNAL/UPDATE_JOURNAL_ENTRIES_REQUEST';
export const UPDATE_JOURNAL_SUCCESS =
  '@@/ACCOUNTING/JOURNAL/UPDATE_JOURNAL_ENTRIES_SUCCESS';
export const UPDATE_JOURNAL_FAILURE =
  '@@/ACCOUNTING/JOURNAL/UPDATE_JOURNAL_ENTRIES_FAILURE';

// 4. delete journal entries
export const DELETE_JOURNAL_REQUEST =
  '@@/ACCOUNTING/JOURNAL/DELETE_JOURNAL_ENTRIES_REQUEST';
export const DELETE_JOURNAL_SUCCESS =
  '@@/ACCOUNTING/JOURNAL/DELETE_JOURNAL_ENTRIES_SUCCESS';
export const DELETE_JOURNAL_FAILURE =
  '@@/ACCOUNTING/JOURNAL/DELETE_JOURNAL_ENTRIES_FAILURE';
