// 1. Login
export const USER_LOGIN_REQUEST = '@@/AUTH/USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = '@@/AUTH/USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = '@@/AUTH/USER_LOGIN_FAILURE';

// 2. Logout
export const USER_LOGOUT = '@@/AUTH/USER_LOGOUT';

// 3. Check profile
export const CHECK_PROFILE_REQUEST = '@@/AUTH/CHECK_PROFILE_REQUEST';
export const CHECK_PROFILE_SUCCESS = '@@/AUTH/CHECK_PROFILE_SUCCESS';
export const CHECK_PROFILE_FAILURE = '@@/AUTH/CHECK_PROFILE_FAILURE';
