// 1. get accounts
export const GET_ACCOUNTS_REQUEST =
  '@@/ACCOUNTING/ACCOUNT/GET_ACCOUNTS_REQUEST';
export const GET_ACCOUNTS_SUCCESS =
  '@@/ACCOUNTING/ACCOUNT/GET_ACCOUNTS_SUCCESS';
export const GET_ACCOUNTS_FAILURE =
  '@@/ACCOUNTING/ACCOUNT/GET_ACCOUNTS_FAILURE';

// 2. create account entries
export const CREATE_ACCOUNT_REQUEST =
  '@@/ACCOUNTING/ACCOUNT/CREATE_ACCOUNT_REQUEST';
export const CREATE_ACCOUNT_SUCCESS =
  '@@/ACCOUNTING/ACCOUNT/CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_FAILURE =
  '@@/ACCOUNTING/ACCOUNT/CREATE_ACCOUNT_FAILURE';

// 3. update account entries
export const UPDATE_ACCOUNT_REQUEST =
  '@@/ACCOUNTING/ACCOUNT/UPDATE_ACCOUNT_REQUEST';
export const UPDATE_ACCOUNT_SUCCESS =
  '@@/ACCOUNTING/ACCOUNT/UPDATE_ACCOUNT_SUCCESS';
export const UPDATE_ACCOUNT_FAILURE =
  '@@/ACCOUNTING/ACCOUNT/UPDATE_ACCOUNT_FAILURE';

// 4. delete account entries
export const DELETE_ACCOUNT_REQUEST =
  '@@/ACCOUNTING/ACCOUNT/DELETE_ACCOUNT_REQUEST';
export const DELETE_ACCOUNT_SUCCESS =
  '@@/ACCOUNTING/ACCOUNT/DELETE_ACCOUNT_SUCCESS';
export const DELETE_ACCOUNT_FAILURE =
  '@@/ACCOUNTING/ACCOUNT/DELETE_ACCOUNT_FAILURE';

// 5. Get specific account
export const GET_SPECIFIC_ACCOUNT_REQUEST =
  '@@/ACCOUNTING/ACCOUNT/GET_SPECIFIC_ACCOUNT_REQUEST';
export const GET_SPECIFIC_ACCOUNT_SUCCESS =
  '@@/ACCOUNTING/ACCOUNT/GET_SPECIFIC_ACCOUNT_SUCCESS';
export const GET_SPECIFIC_ACCOUNT_FAILURE =
  '@@/ACCOUNTING/ACCOUNT/GET_SPECIFIC_ACCOUNT_FAILURE';
